// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vaxi4_lite_top.cpp"
#include "Vaxi4_lite_top___024root__DepSet_h642def98__0.cpp"
#include "Vaxi4_lite_top___024root__DepSet_h0adef376__0.cpp"
#include "Vaxi4_lite_top__Trace__0.cpp"
#include "Vaxi4_lite_top__ConstPool_0.cpp"
#include "Vaxi4_lite_top___024root__Slow.cpp"
#include "Vaxi4_lite_top___024root__DepSet_h642def98__0__Slow.cpp"
#include "Vaxi4_lite_top___024root__DepSet_h0adef376__0__Slow.cpp"
#include "Vaxi4_lite_top__Syms.cpp"
#include "Vaxi4_lite_top__Trace__0__Slow.cpp"
#include "Vaxi4_lite_top__TraceDecls__0__Slow.cpp"
